<a href="https://colab.research.google.com/github/VasylDvorakDS/Text-Classification-NLP-with-RNN-CNN/blob/master/Text_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


# Install TensorFlow




import tensorflow as tf
print(tf.__version__)



2.15.0


In [ ]:
from tensorflow import keras

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [ ]:


# Just a simple test
sentences = [
    "I like eggs and ham.",
    "I love chocolate and bunnies.",
    "I hate onions."
]



In [ ]:


MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)



In [ ]:


print(sequences)



[[1, 3, 4, 2, 5], [1, 6, 7, 2, 8], [1, 9, 10]]


In [ ]:


# To get the word to index mapping.
tokenizer.word_index



{'i': 1,
 'and': 2,
 'like': 3,
 'eggs': 4,
 'ham': 5,
 'love': 6,
 'chocolate': 7,
 'bunnies': 8,
 'hate': 9,
 'onions': 10}

In [ ]:
# use the defaults
data = pad_sequences(sequences)
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [ ]:
MAX_SEQUENCE_LENGTH = 5
data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [ ]:


data = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post')
print(data)



[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 1  9 10  0  0]]


In [ ]:


# too much padding
data = pad_sequences(sequences, maxlen=6)
print(data)



[[ 0  1  3  4  2  5]
 [ 0  1  6  7  2  8]
 [ 0  0  0  1  9 10]]


In [ ]:


# truncation
data = pad_sequences(sequences, maxlen=4)
print(data)



[[ 3  4  2  5]
 [ 6  7  2  8]
 [ 0  1  9 10]]


In [ ]:


data = pad_sequences(sequences, maxlen=4, truncating='post')
print(data)



[[ 1  3  4  2]
 [ 1  6  7  2]
 [ 0  1  9 10]]
